name: super_repository
description: "A new Flutter project."
version: 1.5.3
homepage: https://github.com/abdullah-alwajih/super-repository

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # remote
  dio: ^5.9.2
  connectivity_plus: ^7.1.1

  # local
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0