name: super_repository
description: A new Flutter project.
publish_to: Abdullah-AlWajih
version: 1.1.6
homepage: https://github.com/Abdullah-AlWajih/super-repository

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # remote
  dio: ^5.2.1+1
  connectivity_plus: ^4.0.1

  # local
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1